PARKING_FULL="** Parking is FULL."
ALREADY_EXISTS="** Vehicle with this number already parked in the parking."
SUCCESS="** Vehicle successfully assigned to an empty spot."
NO_VEHICLE="** No vehicle parked with this number."
PARK_CHOICE="1. Please Assign me a parking slot.\n2. Please tell me where my vehicle is located.\n3. Show Parking.\n4. Exit Application.\n\n=> "
INVALID_INPUT="** Please enter a valid choice.\n\n"
VEHICLE_NUM_INPUT="Enter your vehicle number: "
INVALID_CHOICE="** Please enter a valid choice."
EXIT="Exit."
